'use strict';

angular.module('magicBus')
.config(function($translateProvider) {

	$translateProvider.translations('es', {
   		"my_profile": "Mi Perfil",
		"travels": "Viajes",
		"new": "Nuevo",
		"occasional": "Ocasional",
		"diary": "Diario",
		"pending": "Pendientes",
		"historic": "Historial",
		"message": "Mensaje",
		"received": "Recibidos",
		"sent": "Enviados",
		"drivers": "Conductores",
		"registered": "Registrados",
		"travels_for_today": "Viajes Del Dia",
		"parents": "Padres",
		"childs": "Hijos",
		"new_travels_for_childs": "Nuevo Viaje Para Hijo",
		"pending_travels_for_childs": "Viajes Pendientes Para Hijos",
		"log_out": "Salir",
		"es": "ESP",
		"en": "ING",
		"footer": "Magic Bus es una Aplicacion hecha por Francioni - Mancuso Company",
   		"google_sign_in": "Acceder Con Google",
		"email": "EMAIL",
		"create_new_child": "CREAR NUEVO CHICO",
		"surname": "APELLIDO",
		"name": "NOMBRE",
		"document": "DOCUMENTO",
		"age": "EDAD",
		"address": "DIRECCION",
		"telephone": "TELEFONO",
		"celphone": "CELULAR",
		"pregnance_medicine": "OBRA SOCIAL",
		"create": "CREAR",
		"pending_travels": "VIAJES PENDIENTES",
		"destination": "DESTINO",
		"date": "FECHA",
		"scheduler": "HORARIO",
		"driver": "CONDUCTOR",
		"details": "DETALLES",
		"modify": "MODIFICAR",
		"delete": "ELIMINAR",
		"license": "LICENCIA",
		"registered_drivers": "CONDUCTORES REGISTRADOS",
		"save": "GUARDAR",
		"modify_child": "MODIFICAR HIJO",
		"modify_driver": "MODIFICAR CONDUCTOR",
		"create_new_driver": "CREAR NUEVO CONDUCTOR",
		"modify_profile": "MODIFICAR PERFIL",
		"accept": "ACEPTAR",
		"create_new_travel": "CREAR NUEVO VIAJE",
		"pending_parents": "PADRES PENDIENTES",
		"registered_parents": "PADRES REGISTRADOS",
		"registered_childs": "HIJOS REGISTRADOS",
	});

	var language = (navigator.language || navigator.browserLanguage).split('-')[0];
    $translateProvider.preferredLanguage(language);
});